### ISSUE TITLE
Weird tabs ond skipped describe

### ISSUE THREAD

**Issue by Kartoffelsalat** [razvanz/jasmine2-reporter#10]
Hi,

i hace some xdescribe in my test, giving the following output:

skipped: (xdescribe)
multi airport select layer
suggestbox

```
 JASMINE STARTING: 


» quicksearch

    » multi airport select layer

                » suggestbox

                        » regriongroup and region dropdown
                            ✓  the regiongroup dropdown should be filled (4 s)
```

protractor: 2.1.0
jasmine: 2.3.1
jasmine2-reporter: 0.1.1
grunt: 0.4.5
grunt-shell: 1.1.2

OS: Windows 7 Professional 64bit

**Comment by razvanz** [comment]
Noted. Newer versions of Jasmine (I think 2.3.x) have changed reporting functionality. I'll look into updating the reporter to conform with the new API.

**Comment by Kartoffelsalat** [comment]
Thx

**Comment by razvanz** [comment]
Tested with `jasmine-core@2.6.3`:

![screen shot 2017-06-09 at 14 51 38](https://user-images.githubusercontent.com/3844203/26976241-4ac20e2c-4d23-11e7-8cf7-3140a6ecb10d.png)

**Comment by razvanz** [comment]
Tested with `jasmine-core@2.6.3`:

![screen shot 2017-06-09 at 14 53 33](https://user-images.githubusercontent.com/3844203/26976296-8302d15e-4d23-11e7-8143-80b04bf3bf18.png)

**Comment by Kartoffelsalat** [comment]
Sorry for late response, totally forgot to check here again. But im glad you solved it :+1:
