### ISSUE TITLE
Add `emptySuites` option to hide reporting suites with hidden output

### ISSUE THREAD

**Issue by chrismbarr** [razvanz/jasmine2-reporter#15]
I have automatic checking so that when a test fails it sends the output to s Slack channel.  So to reduce the noise in Slack when there's a failure I used these options
```json
stacktrace: false,
pendingSpec: false,
passedSpec: false,
failuresSummary: false
```

Since my tests have a lot of nested suites there is a lot of needless output.  I'd love the ability to hide suites where nothing was reported underneath it with a new option named something like `emptySuites` that defaults to `true` to keep it working the same as it does now.

---
#### With default options:

```
» Suite 1
	» Suite 1.1
		✓  passed test 1.1.1
		✓  passed test 1.1.2
	» Suite 1.2
		✓  passed test 1.2.1
		✓  passed test 1.2.2
» Suite 2
	» Suite 2.1
		✓  passed test 2.1.1
		✗  failed test 1.1.1
	» Suite 1.2
		✓  passed test 2.2.1
		✓  passed test 2.2.2
```

#### With `passedSpec: false`
_(What I'm currently using)_

```
» Suite 1
	» Suite 1.1
	» Suite 1.2
» Suite 2
	» Suite 2.1
		✗  failed test 1.1.1
	» Suite 1.2
```

#### With `passedSpec: false` & `emptySuites: false` 
_(What I'm suggesting)_

```
» Suite 2
	» Suite 2.1
		✗  failed test 2.1.1
```

**Comment by razvanz** [comment]
You could use the "failiure summary" for that.
